### ISSUE TITLE
Triggers does not get backuped on database dump

### ISSUE THREAD

**Issue by lomnido** [memgraph/mgconsole#64]
Can you please advise how to backup Triggers to cypher query language?  

As `DUMP DATABASE;`  backups also CONSTRAINT, but not TRIGGER.  

As saving Triggers using `show triggers;` is not recoverable via cypher query language.

Not even this works:  

`echo "show triggers;" | mgconsole --output-format=cypherl`

**Comment by gitbuda** [comment]
Hi @lomnido! **Thanks a lot** for a very good point 🙏 Somehow, we haven't added triggers to the `DUMP DATABASE;` command. Triggers are slightly semantically different compared to indexes and constraints, but I don't see a reason not to include them inside `DUMP DATABASE;`.

I've created an issue -> https://github.com/memgraph/memgraph/issues/1198 because most work should be done there. In addition, `mgconsole` has to enable convenience by replaying out of `DUMP DATABASE;` and recovering everything. We'll try to deliver that under [v2.12](https://github.com/memgraph/memgraph/milestone/11), but it's not currently high on the priority list. Let us know if that work has to be prioritized.

In the meantime, triggers do get persisted and recovered under the data directory (default is `/var/lib/memgraph/triggers`):
1. Can you use that recovery mechanism (somehow copy/recover that part or the whole data directory)?
2. If 1. is not an option:
  a) Is it possible to maintain the list of triggers on the application side and build your own recovery process just as a workaround?
  b) `SHOW TRIGGERS;` output should have all the data to recover triggers, it's possible to build a simple utility just to collect all triggers and recreate them?

Anyway, I wrote more than planned 😂 Feel free to comment and add more info the issues 💪

**Comment by lomnido** [comment]
@gitbuda Thanks very much for such a detail explanation it helped a LOT!

No worries, I have all my triggers under GIT version control, so there should not be a problem to restore them. Also I will notify my colleagues to do the same in case of adding some new trigger.

**Comment by katarinasupe** [comment]
Hi @lomnido, thanks a lot for opening this issue. Glad to hear you managed to find a workaround, and to track progress, here is the issue that we will work on according to the priority -> https://github.com/memgraph/memgraph/issues/1198

How is your project going? Are you running Memgraph in production, and if yes, are there any other issues you're experiencing? If you need any help, feel free to [schedule a call](https://memgraph.com/office-hours) with our team 😄

**Comment by DavIvek** [comment]
Work in progress under this [PR](https://github.com/memgraph/memgraph/pull/1610).

**Comment by DavIvek** [comment]
Closed as a part of [memgraph/1610](https://github.com/memgraph/memgraph/pull/1610)

**Comment by karmenrabar** [comment]
Hello @lomnido, I am bringing you the good news -  Memgraph has a new release, 2.14., which includes the fix for this issue.  Could you check if the newest version works as expected for you now?

We post all of our release updates on Discord, here's the [link](https://discord.com/channels/842007348272169002/1047507324555767858/1200107892968271956) - feel free to join if you already haven't. :)

**Comment by lomnido** [comment]
@karmenrabar Thanks for notification, it is nice you have Discord. I did not know that.

Of cource new release looks nice and Triggers gets dumped in `DUMP DATABASE` output.

Thanks everyone that has made this possible :heart: .
